### PR TITLE
Attempt Monster, run clippy, attempt to compile.

### PR DESCRIPTION
**Pull request by boomshroom**
What have you done?

Running `cargo test` gives the same failures as master, so I consider that a success.

### CODE REVIEW

**Comment by icefoxen** [comment]
What have *I* done? My goodness, what have *you* done! It looks amazing! I'll try to get some more rigorous tests in there so we can better ensure it works.

**Comment by boomshroom** [comment]
I've mostly been running `clippy` repeatedly and applying the changes it suggests. I noticed after posting this the `test.sh` script, but it seems to just spew text to the console. I should probably use `diff` to track any changes to said output.

**Comment by boomshroom** [comment]
How much am I allowed to change function signatures?

**Comment by boomshroom** [comment]
Hooray! No diff between outputs of test.sh between your original code and my changes!

**Comment by icefoxen** [comment]
Awesome, thank you so much!  Any chance we can automate those sorts of tests, I wonder...

**Pull request merged**
